### ISSUE TITLE
*ERROR  9200 on processing a large file

### ISSUE THREAD

**Issue by numenic** [dr-bill-c/MYSTRAN#10]
When running the attached bulk file (36 load cases, 1365 nodes, CBARs +CBUSHs) , MYSTRAN terminates with this message:

~~~
 *ERROR  9200: PROGRAMMING ERROR IN SUBROUTINE ONE_D_STRESS_OUTPUTS           
               ARRAY OGEL WAS ALLOCATED TO HAVE          424 ROWS. ATTEMPT TO WRITE TO OGEL BEYOND THIS
~~~
The error occurs when dumping Load Case 2. However, when running individual load case 1, 2 or 3, no errors happened.

NX-NASTRAN ha no issue with the same file

[EDIT] add model size data + NX feedback

[fea.nas.zip](https://github.com/dr-bill-c/MYSTRAN/files/6291326/fea.nas.zip)

**Comment by zchlrnr** [comment]
Sorry for the delay. Let me take a look.

**Comment by zchlrnr** [comment]
Successfully recreated on linux operating system as well as Windows. Attempting to isolate pertinant subroutines now. Terribly sorry for the issues, numenic.

**Comment by zchlrnr** [comment]
Have successfully paired it down to this. Far smaller file, only two subcases. I would be that it has to do with matrix allocation for stresses in bush elements, which is a bizzarely fuzzy subject, as how do elements (on a conceptual level) with neither a "modulus" nor an "area" have a "stress"

Now in practice it's not too exotic, but I recall some of the subroutine for Bush element handling was a bit particular, and things like "stress reporting" on elements that shouldn't conceptually be thought of as "stressed" could concieveably not have been a test case that came up in development, especially when thinking about dynamic matrix allocation.

Time will tell.

**Comment by zchlrnr** [comment]
Workaround solved. Commenting out stress stops the problem from occuring.

A more helpful short term fix could be making a set of bushes and requesting stress for all but that set.

A good longterm solution would be to implement proper "stress" reporting for these elements, but in my personal opinion, I think that elements like bushes shouldn't have stresses reported for them at all, but that's in disagreement with how NX Nastran and MSC Nastran work so that isn't a good decision for increasing rates of adoption of Mystran.

**Comment by numenic** [comment]
> Terribly sorry for the issues, numenic.

Hey, that is free software: I never paid any support for Mystran :-)
 
>  I think that elements like bushes shouldn't have stresses reported for them at all

Yes, I agree, but as you said, NX and MSC works this way, and keeping compatibility as possible is important

> Workaround solved. Commenting out stress stops the problem from occuring.

Brillant! Works like a charm. Thanks a lot! I close the issue

**Comment by dr-bill-c** [comment]
The BUSH element has been in error since it was put into MYSTRAN back in 2008. I have finally gotten it completed and agreeing with NASTRAN and will be uploading it soon
