### ISSUE TITLE
MSYTRAN v12.2: regression on CBUSH (ERROR 1959)

### ISSUE THREAD

**Issue by numenic** [dr-bill-c/MYSTRAN#11]
The attached test-case was running fine on V12.1 but fails with V12.2 with the error:

[bulk_model_TC3.zip](https://github.com/dr-bill-c/MYSTRAN/files/6378047/bulk_model_TC3.zip)

``*ERROR  1959: PROGRAMMING ERROR IN SUBROUTINE ELMGM1                         
               BUSH           7 HAS LENGTH (INCL EFFECTS OF OFFSETS) =  9.87E+00. SHOULD BE ZERO``

The bulk runs smoothly on NX-NASTRAN

**Comment by dr-bill-c** [comment]
I found an error in the BUSH code. I was not setting the default offset S=0.5 and that is why the job crashed. I have updated the code in GitHub and am attaching a new zip with the updated 12.2a exe and the nas file you sent along with my f06 after the code fix
[numenic-BUSH-elem.zip](https://github.com/dr-bill-c/MYSTRAN/files/6438095/numenic-BUSH-elem.zip)
Let me know how you make out with the new exe

**Comment by numenic** [comment]
Great ! Issue is solved ! Moreover, CBUSH results are available in .NEU! 
Many thanks!
