### ISSUE TITLE
MYSTRAN V13.1 CBAR + offset is wrong

### ISSUE THREAD

**Issue by numenic** [dr-bill-c/MYSTRAN#19]
[test_case_02.zip](https://github.com/dr-bill-c/MYSTRAN/files/7066256/test_case_02.zip)
In the attached archive are found:

* test_case_02.nas
* test_case_02_NX.f06
* test_case_02_failures.xlsx

failures are found in SPC forces (reactions) and CBAR Engr Forces

The red values in the XLSX files do not match between "Actual" (MSYTRAN) and "Expected" (NX).

[edit] when offset is the same at both extremities, results are OK

**Comment by dr-bill-c** [comment]
Check out the fixed offset
[test_case_02-offset fixed.zip](https://github.com/dr-bill-c/MYSTRAN/files/7228899/test_case_02-offset.fixed.zip)

**Comment by dr-bill-c** [comment]
test_02 fixed (both issues
[test_case_02-offset fixed.zip](https://github.com/dr-bill-c/MYSTRAN/files/7232031/test_case_02-offset.fixed.zip)
)

**Comment by numenic** [comment]
closed with 13.3a
