### ISSUE TITLE
Improve intel portability in subroutine RESTART_DATA_FOR_L3

### ISSUE THREAD

**Issue by enricogombi** [dr-bill-c/MYSTRAN#2]
In subroutine RESTART_DATA_FOR_L3 the following CALL OUTA_HERE gives a compile error in debug configuration with the intel compiler. To enhance the portability, it is suggested to edit the line to CALL OUTA_HERE ( 'N' ) or in any case passing the intended actual parameter

**Comment by dr-bill-c** [comment]
> In subroutine RESTART_DATA_FOR_L3 the following CALL OUTA_HERE gives a compile error in debug configuration with the intel compiler. To enhance the portability, it is suggested to edit the line to CALL OUTA_HERE ( 'N' ) or in any case passing the intended actual parameter

Thanks for pointing this out. The interface module for OUTA_HERE was inadvertently left out of subroutine RESTART_DATA_FOR_L3. The result was that, in Lahey and gfortran at least, the interface was not checked resulting in not being notified of the argument mismatch

**Comment by dr-bill-c** [comment]
Thanks for pointing this out. The interface module for OUTA_HERE was inadvertently left out of subroutine RESTART_DATA_FOR_L3. The result was that, in Lahey and gfortran at least, the interface was not checked resulting in not being notified of the argument mismatch
