### ISSUE TITLE
Build fails under linux: index variable redefined in procedure

### ISSUE THREAD

**Issue by Msegade** [dr-bill-c/MYSTRAN#34]
Build fails on my system using gfortran 12.1 and cmake 3.23. The error is the following:

    [ 39%] Building Fortran object CMakeFiles/LK1.dir/Source/LK1/L1B/CORD_PROC.f90.o
    /usr/bin/f95 -DINTEGER_STAR_8 -I/home/miguel/src/MYSTRAN/Source/INCLUDE -I/home/miguel/src/MYSTRAN/superlu-5.2.2/SRC -I/home/miguel/src/MYSTRAN/f2c/include -g -JBinaries/mod -c /home/miguel/src/MYSTRAN/Source/LK1/L1B/CORD_PROC.f90 -o CMakeFiles/LK1.dir/Source/LK1/L1B/CORD_PROC.f90.o
    /home/miguel/src/MYSTRAN/Source/LK1/L1B/CORD_PROC.f90:1447:59:
    
      408 |                               IF (PRTCORD == 2) CALL PARAM_PRTCORD_OUTPUT ( '33' )
          |                                                                                  2
    ......
     1447 |          WRITE(F06,7302) CID, GA(J), CIDA, (RGA(J,K),K=1,3)
          |                                                           1
    Error: Index variable ‘k’ redefined at (1) in procedure ‘param_prtcord_output’ called from within DO loop at (2)
    /home/miguel/src/MYSTRAN/Source/LK1/L1B/CORD_PROC.f90:1448:59:
    
      408 |                               IF (PRTCORD == 2) CALL PARAM_PRTCORD_OUTPUT ( '33' )
          |                                                                                  2
    ......
     1448 |          WRITE(F06,7302) CID, GB(J), CIDB, (RGB(J,K),K=1,3)
          |                                                           1
    Error: Index variable ‘k’ redefined at (1) in procedure ‘param_prtcord_output’ called from within DO loop at (2)
    /home/miguel/src/MYSTRAN/Source/LK1/L1B/CORD_PROC.f90:1449:59:
    
      408 |                               IF (PRTCORD == 2) CALL PARAM_PRTCORD_OUTPUT ( '33' )
          |                                                                                  2
    ......
     1449 |          WRITE(F06,7302) CID, GC(J), CIDC, (RGC(J,K),K=1,3)
          |                                                           1
    Error: Index variable ‘k’ redefined at (1) in procedure ‘param_prtcord_output’ called from within DO loop at (2)
    make[2]: *** [CMakeFiles/LK1.dir/build.make:1999: CMakeFiles/LK1.dir/Source/LK1/L1B/CORD_PROC.f90.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:360: CMakeFiles/LK1.dir/all] Error 2
    make: *** [Makefile:136: all] Error 2

Apparently in fortran index variables cannot be redefined inside the loop, so this code wont compile. I dont know if there are any options available in the compiler to allow this. Maybe the loops should be rewritten as explained here? https://stackoverflow.com/a/64838060

**Comment by zchlrnr** [comment]
Hello,

I'm terribly sorry for the bug and the delayed answer.

The newer compiler incompatibility with the way that some of our indices are defined is a known issue and we've been putting off dealing with it for a little bit.

Using an older version of the compiler would address the issue, and finishing the updates of these subroutines has jumped to the top of my priority list.

- Zach

**Comment by zchlrnr** [comment]
[mystran_with_fixed_indices_bug.zip](https://github.com/dr-bill-c/MYSTRAN/files/9068433/mystran_with_fixed_indices_bug.zip)
I updated it here. This is a link for my compatriots to download and then work on, in short order.

**Comment by Msegade** [comment]
Thank you very much, that version compiles without any errors!
